language: php

php:
  - 7.0

before_script:
  - mkdir -vp ~/.config/jaggedsoft/
  - mkdir -vp build/logs
  - COMPOSER=composer-test.json composer -vvv install --no-interaction --no-suggest
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar -O coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version
    
script:
  - ./vendor/bin/phpunit --verbose --debug --coverage-clover build/logs/clover.xml --bootstrap vendor/autoload.php php-binance-api-test

after_success:
 - travis_retry php coveralls.phar -v
 - bash <(curl -s https://codecov.io/bash)

branches:
  only: master

cache:
  directories:
  - vendor
  - $HOME/.cache/composer
