language: php

php:
  - 7.0

before_script:
  - mkdir -vp ~/.config/jaggedsoft/
  - mkdir -vp build/logs
  - wget -c -nc --retry-connrefused --tries=0 https://raw.githubusercontent.com/jaggedsoft/php-binance-api/gh-travis/composer-test.json -O composer-test.json
  - wget -c -nc --retry-connrefused --tries=0 https://raw.githubusercontent.com/jaggedsoft/php-binance-api/gh-travis/docs.sh -O docs.sh
  - wget -c -nc --retry-connrefused --tries=0 https://raw.githubusercontent.com/jaggedsoft/php-binance-api/gh-travis/doxy.gen -O doxy.gen
  - wget -c -nc --retry-connrefused --tries=0 https://raw.githubusercontent.com/jaggedsoft/php-binance-api/gh-travis/php-binance-api-test.php -O php-binance-api-test.php
  - wget -c -nc --retry-connrefused --tries=0 https://raw.githubusercontent.com/jaggedsoft/php-binance-api/gh-travis/phpunit.xml -O phpunit.xml
  - COMPOSER=composer-test.json composer -vvv install --no-interaction --no-suggest
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar -O coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

script:
  - ./vendor/bin/phpunit --verbose --debug --coverage-clover build/logs/clover.xml --bootstrap vendor/autoload.php php-binance-api-test

after_success:
 - travis_retry php coveralls.phar -v
 - bash <(curl -s https://codecov.io/bash)
 - cd $TRAVIS_BUILD_DIR
 - chmod +x docs.sh
 - ./docs.sh

branches:
  only: master

env:
  global:
    - GH_REPO_NAME: php-binance-api
    - DOXYFILE: $TRAVIS_BUILD_DIR/doxy.gen
    - GH_REPO_REF: github.com/jaggedsoft/php-binance-api.git
    - DOXY_FILES: $TRAVIS_BUILD_DIR/php-binance-api.php
    - DOXY_FILES_EXCLUDE: $TRAVIS_BUILD_DIR/examples/*

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

cache:
  directories:
  - vendor
  - $HOME/.cache/composer
